export function resolveWizardStepIndex(
  step: string | null,
  stepKeys: readonly string[]
): number {
  const index = step ? stepKeys.indexOf(step) : -1
  return index >= 0 ? index : 0
}

export function syncWizardSearchParams(
  current: URLSearchParams,
  stepKey: string
): URLSearchParams {
  const next = new URLSearchParams(current)
  next.set('step', stepKey)
  if (stepKey !== 'participants') {
    next.delete('participantId')
  }
  return next
}

export function slugify(value: string): string {
  return value
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .replace(/-{2,}/g, '-')
}

export function getNextAutoSlug(
  title: string,
  currentSlug: string | undefined,
  lastAutoGeneratedSlug: string | null
): string {
  if (!currentSlug || currentSlug === lastAutoGeneratedSlug) {
    return slugify(title)
  }

  return currentSlug
}
